### PR TITLE
Fix lots of stuff

### PR DESCRIPTION
**Pull request by AlphaGameDeveloper**
# Fix a few things...
* Development mode ALWAYS ENABLED
* Add `type: ignore` to prevent VSCode warning `Call Expression not allowed in type expression`
* Fix an unresolved import in `cogs.suntsu` for `cogs.combinebot.getSunTsu`

Cheers,
AlphaGameDeveloper

### CODE REVIEW

**Comment by CombineSoldier14** [comment]
Dev mode is meant to be left on. Because when I clone the repo outside of running the script on godot (which doesn't pull anything from .env as it is in gitignore) it's always to test it

**Comment by AlphaGameDeveloper** [comment]
> Dev mode is meant to be left on. Because when I clone the repo outside of running the script on godot (which doesn't pull anything from .env as it is in gitignore) it's always to test it

I am referring to dev mode being enabled in production... 

Screen Shot 2024-09-08 at 12 44 24 PM

**Comment by CombineSoldier14** [comment]
Thought I fixed that if statement... It must have been a git issue

**Comment by AlphaGameDeveloper** [comment]
> Thought I fixed that if statement... It must have been a git issue

I *"git"* it :) (I get it)

**Pull request merged**
